### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [avtuhovich/Program2#1]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**шифрация**
Шифрация (-c) или дешифрация (-d) указанного (в аргументе командной строки) файла. Выходной файл указывается как -o filename.txt, по умолчанию имя формируется из имени входного файла с добавлением расширения.
Алгоритм шифрации XOR. Ключ указывается после -c или -d в шестнадцатеричной системе, длина ключа -- любое целое количество байт.

Command Line: ciphxor [-c key] [-d key] inputname.txt [-o outputname.txt]

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Рекомендуется следующий подход к разработке**:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by JohnKhandygo** [comment]
Ну вы помните, что без тестов проверка не начинается. Напишите, когда можно будет прицельно проверять второе задание.

**Comment by avtuhovich** [comment]
2 задание с тестами

**Comment by JohnKhandygo** [comment]
Это шутка такая? Вы тесты вообще запускали? Они не работают, потому что программа зацикливается. 

Из того, что успел заметить во время беглого осмотра:
- [ ] Пустые `catch` блоки --- это очень плохой стиль. Если вдруг внутри `try` с пустым `catch` случится исключение, программа отработает некорректно, но пользователь не увидит никакого сообщения об ошибке, программа даже не упадет. 
- [ ] Программа попытается что-то сделать, если не указана ни одна из опций `-c`, `-d`. Выглядит не очень правильно. Я бы ожидал сообщение о неверном использовании.
- [ ] По условию задания ключи задаются в шестнадцатеричной системе счисления, у Вас --- это просто строка. Плюс есть ограничение на длину ключа. 
- [ ] Отсутствует .gitignore
- [ ] В maven правила именования для `groupId` и `artifactId` такие же, как и для пакетов в java. Кроме того, принято использовать `groupId` в качестве префикса для всех пакетов в проекте. 
- [ ] Неэффективно организовано чтение из файла: Вы считываете все содержимое файла в память программы (`Files::readAllBytes`). Таким образом, например, при чтении файла размер 2GB программа отожмет не менее 2GB оперативной памяти или упадет, если ей было выделено меньше либо памяти не хватает.

**Comment by avtuhovich** [comment]
Вроде бы часть поправила. А разве по заданию у нас есть ограничения на длинну ключа?

**Comment by JohnKhandygo** [comment]
В байтах ограничения нет, но по условию ключ задаётся в виде строки в шенадцатеричной системе счисления и для того, чтобы он содержал целое количество байт, должны выполняться некоторые ограничения на длину строкового предоставления ключа.

**Comment by JohnKhandygo** [comment]
Меня просто жуть как напрягает коммит в Ваш репозиторий от другого пользователя. Я склонен поставить за это 2, но мы еще обсуждаем с другими преподавателями.

**Comment by avtuhovich** [comment]
У меня был сломан ноутбук и я его только вчера забрала из ремонта

**Comment by avtuhovich** [comment]
У меня был сломан ноутбук

**Comment by JohnKhandygo** [comment]
При этом в тот же день есть другой коммит уже от Вашего пользователя. С заданием все почти нормально, но Вам придется прийти в понедельник и объяснить мне, как все это работает.

**Comment by JohnKhandygo** [comment]
Сделано на 5, -0.5 балла за последнюю аттестацию. Итого, второе задание зачтено на 4.5.
