### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [avtuhovich/Program2#3]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Русские шашки**
Реализовать игру Русские шашки для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Русские_шашки)

**Comment by avtuhovich** [comment]
https://github.com/avtuhovich/Checkers - репозиторий 3 задания

**Comment by JohnKhandygo** [comment]
Перенес описание задания в новый репозиторий, все замечания будут появляться там.
